name: release
on:
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - name: Pull code
      uses: actions/checkout@v1
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build -- --prod
    - name: Publish to npm
      run: npm publish
      working-directory: ./dist/luxon-angular
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
